"""Command identifiers retained for API/source-layout parity with agave_pyclient.

The headless Vulkan package does not serialize command buffers. ``AgaveRenderer``
passes typed arguments directly to C++ through nanobind.
"""

COMMANDS = {
    "SESSION": 0,
    "ASSET_PATH": 1,
    "LOAD_OME_TIF": 2,
    "EYE": 3,
    "TARGET": 4,
    "UP": 5,
    "APERTURE": 6,
    "CAMERA_PROJECTION": 7,
    "FOCALDIST": 8,
    "EXPOSURE": 9,
    "MAT_DIFFUSE": 10,
    "MAT_SPECULAR": 11,
    "MAT_EMISSIVE": 12,
    "RENDER_ITERATIONS": 13,
    "STREAM_MODE": 14,
    "REDRAW": 15,
    "SET_RESOLUTION": 16,
    "DENSITY": 17,
    "FRAME_SCENE": 18,
    "MAT_GLOSSINESS": 19,
    "ENABLE_CHANNEL": 20,
    "SET_WINDOW_LEVEL": 21,
    "ORBIT_CAMERA": 22,
    "SKYLIGHT_TOP_COLOR": 23,
    "SKYLIGHT_MIDDLE_COLOR": 24,
    "SKYLIGHT_BOTTOM_COLOR": 25,
    "LIGHT_POS": 26,
    "LIGHT_COLOR": 27,
    "LIGHT_SIZE": 28,
    "SET_CLIP_REGION": 29,
    "SET_VOXEL_SCALE": 30,
    "AUTO_THRESHOLD": 31,
    "SET_PERCENTILE_THRESHOLD": 32,
    "MAT_OPACITY": 33,
    "SET_PRIMARY_RAY_STEP_SIZE": 34,
    "SET_SECONDARY_RAY_STEP_SIZE": 35,
    "BACKGROUND_COLOR": 36,
    "SET_ISOVALUE_THRESHOLD": 37,
    "SET_CONTROL_POINTS": 38,
    "LOAD_VOLUME_FROM_FILE": 39,
    "SET_TIME": 40,
    "SET_BOUNDING_BOX_COLOR": 41,
    "SHOW_BOUNDING_BOX": 42,
    "TRACKBALL_CAMERA": 43,
    "LOAD_DATA": 44,
    "SHOW_SCALE_BAR": 45,
    "SET_FLIP_AXIS": 46,
    "SET_INTERPOLATION": 47,
    "SET_CLIP_PLANE": 48,
    "SET_COLOR_RAMP": 49,
    "SET_MIN_MAX_THRESHOLD": 50,
    "SET_SKYLIGHT_ROTATION": 51,
    "SHOW_TIME_STAMP": 52,
    "SET_TIME_STAMP_FORMAT": 53,
    "SET_MULTICHANNEL_BLEND": 54,
}
