[tox]
skipsdist = True
envlist = py37, py38, py39, lint

[testenv:lint]
deps =
    .[test]
commands =
    ruff check agave_pyclient
    ruff format --check agave_pyclient

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    .[test]
commands =
    pytest --basetemp={envtmpdir} --cov-report html --cov=agave_pyclient agave_pyclient/tests/
