<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>agave</string>
	<key>CFBundleIcons</key>
	<dict>
		<key>CFBundlePrimaryIcon</key>
		<dict>
			<key>CFBundleIconFiles</key>
			<array>
				<string>dmg-icon.icns</string>
			</array>
			<key>UIPrerenderedIcon</key>
			<false/>
		</dict>
	</dict>
	<key>CFBundleIdentifier</key>
	<string>org.allencell.agave</string>
	<key>CFBundleName</key>
	<string>AGAVE</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>@PROJECT_VERSION@</string>
	<key>CFBundleShortVersionString</key>
	<string>@PROJECT_VERSION@</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>org.allencell.agave</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>agave</string>
			</array>
		</dict>
	</array>
	<key>LSMinimumSystemVersion</key>
	<string>@PACKAGE_OSX_TARGET@</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>NSHighResolutionCapable</key>
	<string>true</string>
	<key>Application Category</key>
	<string>Education</string>
</dict>
</plist>
